name: kyc2
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^2.0.2    
  sqflite: any
  path_provider: any
  intl: ^0.17.0
  dotted_border: any
  provider: ^6.0.0
  http: any
  flutter_signature_pad: any
  path: any
  shared_preferences: ^2.0.9 
  uuid: ^3.0.5
  flutter_shared_widgets:
    #path: /Users/raghunathan/AB_POC/flutter_module/updated/updated_shared_widget
    git:
      url: https://github.com/angel-one/flutter-shared-widgets.git
      ref: develop
  navigator:
    #path: /Users/raghunathan/AB_POC/flutter_module/navigator
    git:
      url: https://github.com/angel-one/flutter-navigation-plugin.git
      ref: develop
  digilocker:
    git:
      url: https://github.com/angel-one/flutter-digilocker-sdk.git
      ref: master
  esign:
    git:
      url: https://github.com/angel-one/flutter-esign.git
      ref: master
  analytic_plugin:    
    #path: /Users/raghunathan/AB_POC/flutter_module/analytic_related/analytic_develop
    git:
      url: https://github.com/angel-msil/flutter-analytics-plugin.git
      ref: develop

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.1
  hypersnapsdk_flutter: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: any
  json_annotation: 4.0.0
  flutter_svg: 0.22.0
  permission_handler: 8.3.0
  url_launcher: ^6.0.20

dependencies_overrides:
 intl: ^0.17.0  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  assets:
    #- assets/icons/
    #- assets/images/
    - flows.json
#    - lib/constants/config/uat.json
#    - lib/constants/config/prod.json
#    - lib/constants/config/cug.json
    - packages/kyc2/js/config/uat.json
    - packages/kyc2/js/config/prod.json
    - packages/kyc2/js/config/cug.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Barlow
      fonts:
        - asset: fonts/Barlow-Black.ttf
        - asset: fonts/Barlow-BlackItalic.ttf
        - asset: fonts/Barlow-Bold.ttf
        - asset: fonts/Barlow-BoldItalic.ttf
        - asset: fonts/Barlow-ExtraBold.ttf
        - asset: fonts/Barlow-ExtraBoldItalic.ttf
        - asset: fonts/Barlow-ExtraLight.ttf
        - asset: fonts/Barlow-ExtraLightItalic.ttf
        - asset: fonts/Barlow-Italic.ttf
        - asset: fonts/Barlow-Light.ttf
        - asset: fonts/Barlow-LightItalic.ttf
        - asset: fonts/Barlow-Medium.ttf
        - asset: fonts/Barlow-MediumItalic.ttf
        - asset: fonts/Barlow-Regular.ttf
        - asset: fonts/Barlow-SemiBold.ttf
        - asset: fonts/Barlow-SemiBoldItalic.ttf
        - asset: fonts/Barlow-Thin.ttf
        - asset: fonts/Barlow-ThinItalic.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.angelbroking.kycsdk
    iosBundleIdentifier: com.angelbroking.kycsdk
